---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-telegram-admin-k8s-deployment
spec:
  selector:
    matchLabels:
      app: prod-telegram-admin-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: prod-telegram-admin-k8s
    spec:
      containers:
        - name: prod-telegram-admin-k8s
          image: registry.digitalocean.com/resty-registry/prod-telegram-admin:latest
          ports:
            - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: prod-telegram-admin-service
spec:
  selector:
    app: prod-telegram-admin-k8s
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3002
