export enum OrdersEvents {
	CREATED = "ORDER_CREATED",
	CLOSED = "ORDER_CLOSED",
	WAITING_FOR_MANUAL_PAY = "ORDER_WAITING_FOR_MANUAL_PAY",
	CONFIRM = "ORDER_CONFIRM",
	USER_ADDED = "ORDER_USER_ADDED",
	TABLE_ADDED = "ORDER_TABLE_ADDED",
	TABLE_REMOVED = "ORDER_TABLE_REMOVED"
}
