export enum OrdersEvents {
	CREATED = "ORDER_CREATED",
	CLOSED = "ORDER_CLOSED",
	PRODUCT_ADDED = "ORDER_PRODUCT_ADDED",
	PRODUCT_REMOVED = "ORDER_PRODUCT_REMOVED",
	USER_ADDED = "ORDER_USER_ADDED",
	TABLE_ADDED = "ORDER_TABLE_ADDED",
	TABLE_REMOVED = "ORDER_TABLE_REMOVED"
}
