export enum OrdersEvents {
	CREATED = "CREATED",
	CLOSED = "CLOSED",
	WAITING_FOR_MANUAL_PAY = "WAITING_FOR_MANUAL_PAY",
	REQUEST_TO_CONFIRM = "REQUEST_TO_CONFIRM",
	CONFIRM = "CONFIRM",
	USER_ADDED = "USER_ADDED",
	TABLE_ADDED = "TABLE_ADDED",
	TABLE_REMOVED = "TABLE_REMOVED"
}
