name: Deploy to Dev

#on: [push]
on:
  push:
    branches:
      - dev

env:
  REGISTRY: "registry.digitalocean.com/resty-registry"
  TELEGRAM_ADMIN: "telegram-admin"

jobs:
  deploy:
    name: Build Telegram Admin Image
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: executing git pull on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: resty
          key: ${{ secrets.SSHKEY }}
          port: 22
          command_timeout: 30m
          envs: TELEGRAM_ADMIN,GITHUB_SHA,REGISTRY
          script: |
            cd /home/resty/telegram-admin
            git fetch
            git checkout dev
            git pull
            docker system prune -f --volumes
            docker build --no-cache -f Dockerfile.dev -t $(echo $REGISTRY)/$(echo $TELEGRAM_ADMIN):latest .

            doctl registry login
            docker push $(echo $REGISTRY)/$(echo $TELEGRAM_ADMIN):latest
          
            cd /home/resty/k8s
            kubectl apply -f cloudflared.yaml
            cd /home/resty/telegram-admin
            kubectl delete -f telegram-admin.k8s.yaml
            kubectl apply -f telegram-admin.k8s.yaml
